version: "2.32.4"
name: docker-compose

services:
  database:
    image: postgres:15.10-alpine3.20
    container_name: postgres_database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: docker-compose
    networks:
      - database_network
    volumes:
      - database_data:/var/lib/postgresql/data

  frontend:
    image: nginx:stable-alpine3.20
    container_name: nginx_frontend
    ports:
      - "80:80"
    networks:
      - database_network
    volumes:
      - ./frontend:/usr/share/nginx/html:ro

  backend:
    image: node:20-alpine
    container_name: node_backend
    ports:
      - "8002:3000"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: sh -c "npm install express cors pg && node server.js"
    depends_on:
      - database
    networks:
      - database_network

networks:
  database_network:
    external: true
    name: mydatabase_network

volumes:
  database_data:
    external: true
    name: mydatabase_data
